<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tabel List Riwayat Fraud Assesment</name>
   <tag></tag>
   <elementGuidId>d990a3a4-f356-4f99-9a72-51f23000ab82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>table</value>
      <webElementGuid>8fc9ed0d-6556-41e5-839c-292729b6b724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Table Fraud Assesment</value>
      <webElementGuid>16a54241-1059-41f9-878d-2fe33c2eab49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-aria7861130085-:r6:</value>
      <webElementGuid>6d18f24d-3372-411b-9a2c-75d74c79797a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>grid</value>
      <webElementGuid>2408fcf1-7036-4080-bf9e-16a2ed2aa26f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5bd68834-646d-45ba-b431-d6dd5c79d1cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>min-w-full h-auto table-auto w-full</value>
      <webElementGuid>1742ec77-4349-4139-9e1b-92fedf76bf66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ID ASSESMENTPENGISI ASSESMENTREVIEWERTANGGAL PEMBUATANSTATUSHASIL INTERNALHASIL EXTERNALAKSI5purh5cucz5nAdmin Perusahaan-11 June 2024, 03:28SelesaiBelum dinilaiBelum dinilaiLihat Detail7ts07snoazfqAdmin Perusahaan-11 June 2024, 03:33Belum SelesaiBelum dinilaiBelum dinilaiLihat Detailbpc0phbfg9ybAdmin Perusahaan-11 June 2024, 03:30SelesaiBelum dinilaiBelum dinilaiLihat Detailps25zjndzu1oAdmin Perusahaan-11 June 2024, 03:29SelesaiBelum dinilaiBelum dinilaiLihat Detailvgj950aao9hkAdmin Perusahaan-07 June 2024, 10:59SelesaiBelum dinilaiBelum dinilaiLihat Detail</value>
      <webElementGuid>8c12f9ef-6898-4c24-b35c-2700085a6fe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-aria7861130085-:r6:&quot;)</value>
      <webElementGuid>9b559632-ef3e-49a2-8977-0092f061a479</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//table[@id='react-aria7861130085-:r6:']</value>
      <webElementGuid>6f58fce6-c566-4785-a3b8-9a0d8f687253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Isi Fraud Assesment'])[1]/following::table[1]</value>
      <webElementGuid>e17b5d96-b105-4897-96c3-de07ccf0a69a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Riwayat Fraud Assesment'])[1]/following::table[1]</value>
      <webElementGuid>8ed581f9-d97f-4d8c-9a14-3193ac0e5158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table</value>
      <webElementGuid>468ebf5c-1652-4360-beb1-0e119accef13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//table[@id = 'react-aria7861130085-:r6:' and (text() = 'ID ASSESMENTPENGISI ASSESMENTREVIEWERTANGGAL PEMBUATANSTATUSHASIL INTERNALHASIL EXTERNALAKSI5purh5cucz5nAdmin Perusahaan-11 June 2024, 03:28SelesaiBelum dinilaiBelum dinilaiLihat Detail7ts07snoazfqAdmin Perusahaan-11 June 2024, 03:33Belum SelesaiBelum dinilaiBelum dinilaiLihat Detailbpc0phbfg9ybAdmin Perusahaan-11 June 2024, 03:30SelesaiBelum dinilaiBelum dinilaiLihat Detailps25zjndzu1oAdmin Perusahaan-11 June 2024, 03:29SelesaiBelum dinilaiBelum dinilaiLihat Detailvgj950aao9hkAdmin Perusahaan-07 June 2024, 10:59SelesaiBelum dinilaiBelum dinilaiLihat Detail' or . = 'ID ASSESMENTPENGISI ASSESMENTREVIEWERTANGGAL PEMBUATANSTATUSHASIL INTERNALHASIL EXTERNALAKSI5purh5cucz5nAdmin Perusahaan-11 June 2024, 03:28SelesaiBelum dinilaiBelum dinilaiLihat Detail7ts07snoazfqAdmin Perusahaan-11 June 2024, 03:33Belum SelesaiBelum dinilaiBelum dinilaiLihat Detailbpc0phbfg9ybAdmin Perusahaan-11 June 2024, 03:30SelesaiBelum dinilaiBelum dinilaiLihat Detailps25zjndzu1oAdmin Perusahaan-11 June 2024, 03:29SelesaiBelum dinilaiBelum dinilaiLihat Detailvgj950aao9hkAdmin Perusahaan-07 June 2024, 10:59SelesaiBelum dinilaiBelum dinilaiLihat Detail')]</value>
      <webElementGuid>aeabe752-f44a-477e-92ec-f9b11631803e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
