<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Notifications of Password Not Valid</name>
   <tag></tag>
   <elementGuidId>66d489d9-b305-4559-b1a0-d59c06c48143</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[6]/div/div[2]/div&#xd;
</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-slot = 'error-message' and @class = 'text-tiny text-danger' and (text() = 'Password tidak boleh kosong' or . = 'Password tidak boleh kosong') and contains(@alttext, 'Password tidak boleh kurang dari 8 karakter')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>33605166-732f-4193-8fd2-3d39d2ce2d36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>error-message</value>
      <webElementGuid>cd04b1e6-d919-43db-a350-509911c63891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-tiny text-danger</value>
      <webElementGuid>9a4c92cf-cd82-4e22-a545-dff3ba0c41ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-aria9066488081-:r36:</value>
      <webElementGuid>1170e5de-de82-4332-8a29-b419cdb1e97f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Password tidak boleh kosong</value>
      <webElementGuid>43ef02df-d3fc-4df7-b880-c378a75ffc71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-aria9066488081-:r36:&quot;)</value>
      <webElementGuid>12d24641-1ef9-41d0-8843-f556fd191edc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>alttext</name>
      <type>Main</type>
      <value>Password tidak boleh kurang dari 8 karakter</value>
      <webElementGuid>423a0156-db0b-447d-83e5-687492ac65c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-aria9066488081-:r36:']</value>
      <webElementGuid>d6b9df87-0d51-4fb7-8bd2-f68f08ae35e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::div[3]</value>
      <webElementGuid>c42e48bd-e202-46d5-9f15-9948be1a8ddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username'])[1]/following::div[7]</value>
      <webElementGuid>7e3c12bb-5114-4700-af5d-c242c5063517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Konfirmasi Password'])[1]/preceding::div[1]</value>
      <webElementGuid>24f148b7-f87c-45d5-a4b3-10fdf6246726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Required'])[1]/preceding::div[3]</value>
      <webElementGuid>42df434d-4cc0-4d02-a1cc-a4d4b40f6f3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Password tidak boleh kosong']/parent::*</value>
      <webElementGuid>30ab6283-2487-4827-a697-bd10af91e1b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div</value>
      <webElementGuid>9aff1222-0424-4580-ae0d-92380f4fc3a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-aria9066488081-:r36:' and (text() = 'Password tidak boleh kosong' or . = 'Password tidak boleh kosong')]</value>
      <webElementGuid>0fe8c448-f94e-4e23-80fe-71a3fd126f0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
