<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Notifications of Konfirmasi Password Not Valid</name>
   <tag></tag>
   <elementGuidId>2875c860-2d88-43dd-85bf-22118ec5e8c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[7]/div/div[2]/div&#xd;
</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-slot = 'error-message' and @class = 'text-tiny text-danger' and (text() = 'Password tidak boleh kosong' or . = 'Password tidak boleh kosong') and contains(@alttext, 'Password tidak boleh kurang dari 8 karakter')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7e3dbe7a-585e-46b5-bc76-0798b8a92896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>error-message</value>
      <webElementGuid>270e39e4-e779-44f6-96ce-4ae7a8afead5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-tiny text-danger</value>
      <webElementGuid>155bbc6d-e40d-4a62-9d41-ccf629ae788d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-aria9066488081-:r36:</value>
      <webElementGuid>a98ee775-88ea-4e13-9d33-347b7b03545f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Password tidak boleh kosong</value>
      <webElementGuid>a1f80e37-bc48-4aca-b524-03b4e03db9ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-aria9066488081-:r36:&quot;)</value>
      <webElementGuid>7017657d-53b5-4fb7-ac87-c773cad648bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>alttext</name>
      <type>Main</type>
      <value>Password tidak boleh kurang dari 8 karakter</value>
      <webElementGuid>8c71a42b-8842-4e98-b827-f23327336954</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-aria9066488081-:r36:']</value>
      <webElementGuid>07171781-7b3c-49e0-b728-2485abe10f43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::div[3]</value>
      <webElementGuid>89cae117-3fc1-4057-a593-4da336db6ad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username'])[1]/following::div[7]</value>
      <webElementGuid>67aa35a0-4a48-4cc4-b45d-96e54f6b57e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Konfirmasi Password'])[1]/preceding::div[1]</value>
      <webElementGuid>33522888-2e34-4289-8358-4abba2c12d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Required'])[1]/preceding::div[3]</value>
      <webElementGuid>e169114f-5760-4b20-afce-45c3451779e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Password tidak boleh kosong']/parent::*</value>
      <webElementGuid>dffceb58-f29d-478e-99e9-33cde19a213a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div</value>
      <webElementGuid>8159bbe7-6c74-40c4-ba30-fbc52b962175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-aria9066488081-:r36:' and (text() = 'Password tidak boleh kosong' or . = 'Password tidak boleh kosong')]</value>
      <webElementGuid>4520088b-648d-40fe-a537-e02b8a0994a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
