<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Action Button Fixed Reviewer</name>
   <tag></tag>
   <elementGuidId>6ef00c8c-7f53-4d85-8313-be0a28ca9478</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @id = 'react-aria7137989381-:r3k:' and (text() = 'Nonaktif,' or . = 'Nonaktif,')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Emma Jones'])[1]/following::button[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>55bda6fe-4cbd-458d-9cad-f98ce726a2cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>trigger</value>
      <webElementGuid>e6a91cfd-56ea-469f-aabc-e4efbbba4424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative px-3 gap-3 w-full inline-flex flex-row items-center shadow-sm tap-highlight-transparent h-10 min-h-10 rounded-medium bg-danger-50 text-danger dark:text-danger-500 data-[hover=true]:bg-danger-100 group-data-[focus=true]:bg-danger-50 outline-none data-[focus-visible=true]:z-10 data-[focus-visible=true]:outline-2 data-[focus-visible=true]:outline-focus data-[focus-visible=true]:outline-offset-2</value>
      <webElementGuid>3598f1ae-48bf-4df5-9011-363ab6537b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b8165f28-999a-40b2-91b9-c13070d22727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>832ebd47-e974-4f0a-9d0a-425f23676782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-aria7137989381-:r3k:</value>
      <webElementGuid>935f53f9-b7ac-446e-a789-9f555849a6aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>react-aria7137989381-:r3p: react-aria7137989381-:r3k:</value>
      <webElementGuid>845eb8a9-b4f3-41be-8f86-f453b9796d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>4eef759e-cc2b-4d7e-9f57-914c079533a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>43775ccb-1558-48d8-9ebf-aa84cc311946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>aa16a162-0e13-4b4f-b176-bb463a792a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nonaktif,</value>
      <webElementGuid>8e192078-7cdb-4ed8-81da-372f8d3f322f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-aria7137989381-:r3k:&quot;)</value>
      <webElementGuid>bb57e31f-25fb-463b-a245-83a212a3f541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hover</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>058a579e-0ee2-407e-852e-8671ee99e43d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='react-aria7137989381-:r3k:']</value>
      <webElementGuid>b3e815b2-1920-488d-8b1a-ac8b3b3e1a0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='react-aria7137989381-:ro:']/tbody/tr[2]/td[4]/div/div[2]/button</value>
      <webElementGuid>34cf6e2f-29a8-4440-8885-17414fae6070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='itadoriyuuji@yopmail.com'])[1]/following::button[1]</value>
      <webElementGuid>1f4845b1-4f62-4e5a-9d74-fec93b57f2f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Itadori Yuuji'])[1]/following::button[1]</value>
      <webElementGuid>0f444d9f-d483-48ab-a481-92247b0db3be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/div/div[2]/button</value>
      <webElementGuid>e29d2834-a2c3-4b41-9b13-0eb9759425fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'react-aria7137989381-:r3k:' and (text() = 'Nonaktif,' or . = 'Nonaktif,')]</value>
      <webElementGuid>b64d257c-2e81-4178-8477-e1d363f92a3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='react-aria8020494027-:r1c:']</value>
      <webElementGuid>f6dbc1ea-60df-41f9-afa3-de5baf245a1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='react-aria8020494027-:ro:']/tbody/tr[2]/td[4]/div/div[2]/button</value>
      <webElementGuid>d4670e0b-1568-4c28-a02d-c3f71dcc1592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'react-aria8020494027-:r1c:' and (text() = 'Nonaktif,' or . = 'Nonaktif,')]</value>
      <webElementGuid>70260297-71c7-411a-8768-d769b7ce8f92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
