<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Aktif,</name>
   <tag></tag>
   <elementGuidId>cf664f0e-451b-48c0-820c-7855ec071362</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='react-aria8020494027-:r14:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fc446f6a-0169-41e6-b1b1-748e28cf2f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>trigger</value>
      <webElementGuid>4c56a406-863c-4314-9ca7-9b7dd237d3b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative px-3 gap-3 w-full inline-flex flex-row items-center shadow-sm tap-highlight-transparent h-10 min-h-10 rounded-medium bg-success-50 text-success-600 dark:text-success data-[hover=true]:bg-success-100 group-data-[focus=true]:bg-success-50 outline-none data-[focus-visible=true]:z-10 data-[focus-visible=true]:outline-2 data-[focus-visible=true]:outline-focus data-[focus-visible=true]:outline-offset-2</value>
      <webElementGuid>bfe91734-d40f-4ef6-8578-7eae4c4ef769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e7bc07e6-752f-4c29-9d02-aaf308f54770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>3cf068b1-fb49-46d2-95b3-0602bd4c2f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-aria8020494027-:r14:</value>
      <webElementGuid>e8244035-798a-44ac-b704-74e39f4d92a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>react-aria8020494027-:r19: react-aria8020494027-:r14:</value>
      <webElementGuid>3e70bde0-0866-498a-af5c-c92ebd34fcf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>eebdc273-fb11-4691-9b2d-af92e6a0e22a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4d7bfe89-fc3f-4be8-979c-89860ad7ec4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>65d5b559-cc36-4b64-aa6e-1c7b06e0a888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hover</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>620deec7-c409-414f-a8fd-516688569051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aktif,</value>
      <webElementGuid>e57e63fd-26b3-4a40-b2af-4bdb04a4ec9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-aria8020494027-:r14:&quot;)</value>
      <webElementGuid>1dd1e6c1-c208-4865-963f-8c31410d1b3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='react-aria8020494027-:r14:']</value>
      <webElementGuid>b83cfc02-acc6-470c-92d0-478b9f9e5492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='react-aria8020494027-:ro:']/tbody/tr/td[4]/div/div[2]/button</value>
      <webElementGuid>29f2652a-8d8b-4ba0-a161-eecdbacb011a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bob@example.com'])[1]/following::button[1]</value>
      <webElementGuid>7c354b0c-8f04-4d5f-8bd5-8bc67eef9bee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bob Marley'])[1]/following::button[1]</value>
      <webElementGuid>dd2ca0c0-d1bf-4851-8bdd-e7a183e2e4c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>aae538ce-77de-4e64-8e35-f7485630e402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'react-aria8020494027-:r14:' and (text() = 'Aktif,' or . = 'Aktif,')]</value>
      <webElementGuid>2c599267-aca7-473c-afbc-95814fe31765</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
