<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Nomor 15 - Belum ada</name>
   <tag></tag>
   <elementGuidId>02bce3da-7025-4073-995c-295e3867f041</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'radio' and @name = 'assesment.14.answer' and (text() = 'Belum ada' or . = 'Belum ada')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label[name=&quot;assesment.14.answer&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@name='assesment.14.answer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>f08e40b6-2e57-4f8d-9c77-ab4a113bb482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>group relative max-w-fit inline-flex items-center justify-start cursor-pointer tap-highlight-transparent p-2 -m-2</value>
      <webElementGuid>42894791-9007-43f7-a7fe-2391d911d865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>f26d24f1-3ec6-44a3-82e4-9a566eda5ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>assesment.14.answer</value>
      <webElementGuid>055dd43b-08f1-4df5-9568-8fd02e68bb48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hover</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4743cf44-f5c1-42c4-8a60-1b2b33e80f74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hover-unselected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cffe5f29-93c5-43dd-ad80-36211b5146c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5ab3d427-7a96-4f50-9b7f-023cf8526a07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Belum ada</value>
      <webElementGuid>e191f7f4-bef1-402a-9f07-777b3b8eb62d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-aria6291184222-:rsu:&quot;)/div[@class=&quot;flex flex-col flex-wrap gap-2 data-[orientation=horizontal]:flex-row&quot;]/label[@class=&quot;group relative max-w-fit inline-flex items-center justify-start cursor-pointer tap-highlight-transparent p-2 -m-2&quot;]</value>
      <webElementGuid>b8d6220e-32e5-4aed-b174-7d8494df1fca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@name='assesment.14.answer']</value>
      <webElementGuid>f99267f0-9983-441b-a63a-50d5f83afaed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-aria6291184222-:rsu:']/div/label</value>
      <webElementGuid>92deff04-8980-459f-896d-427f88e3350e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum ada'])[14]/following::label[1]</value>
      <webElementGuid>ad83da91-c260-4329-9027-570cd22e6d3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ada, belum lengkap'])[14]/following::label[2]</value>
      <webElementGuid>a9ac80bf-fb80-4a68-8c17-a8e34f9a70d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ada, belum lengkap'])[15]/preceding::label[1]</value>
      <webElementGuid>ec65f9a0-cc7d-4f79-bd5f-0615e8e07b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div/div/div/div/label</value>
      <webElementGuid>78badbc2-fd8e-4c9b-abbd-79da1b37801a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@type = 'radio' and @name = 'assesment.14.answer' and (text() = 'Ada, dan sudah lengkap' or . = 'Ada, dan sudah lengkap')]</value>
      <webElementGuid>b5ebad98-d1ad-442d-983e-13917143c5ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
