<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Nomor 13 - Belum ada</name>
   <tag></tag>
   <elementGuidId>9c3a01f8-09b4-4b62-9e54-0bd17cfdb68f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'radio' and @name = 'assesment.12.answer' and (text() = 'Belum ada' or . = 'Belum ada')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label[name=&quot;assesment.12.answer&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@name='assesment.12.answer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>0ba696d8-ded1-45f8-b310-945ee5082ec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>group relative max-w-fit inline-flex items-center justify-start cursor-pointer tap-highlight-transparent p-2 -m-2</value>
      <webElementGuid>4fbbd99d-6dc8-4adf-a121-3eaa6d1c9272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>03f760a2-2e01-4e2c-a269-e526e8b2eddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>assesment.12.answer</value>
      <webElementGuid>5a0ff596-19ee-4434-8089-8c4951e6cb81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hover</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d9c69eff-ed19-4343-a038-3e2e1210ebdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hover-unselected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8e5f7b1e-f393-4be8-9edf-49dde68c51e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8b48aade-8008-49d2-b8cc-4e05b0fab7fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Belum ada</value>
      <webElementGuid>781e0f7a-c25f-4aa4-b38d-f3f3251e1532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-aria6291184222-:rsc:&quot;)/div[@class=&quot;flex flex-col flex-wrap gap-2 data-[orientation=horizontal]:flex-row&quot;]/label[@class=&quot;group relative max-w-fit inline-flex items-center justify-start cursor-pointer tap-highlight-transparent p-2 -m-2&quot;]</value>
      <webElementGuid>d63a33c7-1882-4f7a-94f6-fec4a50e9fad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@name='assesment.12.answer']</value>
      <webElementGuid>3d4ef9ab-aaad-4cac-8b43-b3945299bf8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-aria6291184222-:rsc:']/div/label</value>
      <webElementGuid>c41d8a59-197a-466f-9e0c-4ee1100d5b5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum ada'])[12]/following::label[1]</value>
      <webElementGuid>10995677-5e40-49d6-a53a-aeaae68b9374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ada, belum lengkap'])[12]/following::label[2]</value>
      <webElementGuid>87b3cfce-a74d-4ae0-8532-2183df294c2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ada, belum lengkap'])[13]/preceding::label[1]</value>
      <webElementGuid>68b2d342-de57-45eb-a555-9f1e24240532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div/div/div/div/label</value>
      <webElementGuid>350f93f8-8998-40f8-8ff8-cf80a378abc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@type = 'radio' and @name = 'assesment.12.answer' and (text() = 'Ada, dan sudah lengkap' or . = 'Ada, dan sudah lengkap')]</value>
      <webElementGuid>fd8c1c20-ed17-4d17-801f-d6302ba00002</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
