<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Nomor 04 - Ada, belum lengkap</name>
   <tag></tag>
   <elementGuidId>ee4a5ec0-7616-48b6-b613-1ce905ff5fc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'radio' and @name = 'assesment.3.answer' and (text() = 'Ada, belum lengkap' or . = 'Ada, belum lengkap')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label[name=&quot;assesment.3.answer&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@type = 'radio' and @name = 'assesment.3.answer' and (text() = 'Ada, dan sudah lengkap' or . = 'Ada, dan sudah lengkap')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ba1a75a1-2480-44c4-8915-169f2b92ba85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>group relative max-w-fit inline-flex items-center justify-start cursor-pointer tap-highlight-transparent p-2 -m-2</value>
      <webElementGuid>230da58d-4eac-455c-b517-2009761dcac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ba78d0b0-cb79-4958-a6d4-698b0de6bf53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>assesment.3.answer</value>
      <webElementGuid>a02a6cfb-2b8a-44c1-870c-ade4b65072a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hover</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5b22e424-f8f4-47fb-85ca-8f8f6b5fcd87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hover-unselected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fa9d513a-aadd-4dc1-9dd5-a12e6503c906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3a0c5d8e-4f3c-4b8d-8273-031a4faab40e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ada, belum lengkap</value>
      <webElementGuid>0ae67de0-de80-4158-88b8-d10b42e762de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-aria6291184222-:r63:&quot;)/div[@class=&quot;flex flex-col flex-wrap gap-2 data-[orientation=horizontal]:flex-row&quot;]/label[@class=&quot;group relative max-w-fit inline-flex items-center justify-start cursor-pointer tap-highlight-transparent p-2 -m-2&quot;]</value>
      <webElementGuid>24549b79-ddca-4246-8a9d-db6e5ba5e687</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@name='assesment.3.answer']</value>
      <webElementGuid>2b8bb2e8-8c6b-4039-9347-2235ae504b64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-aria6291184222-:r63:']/div/label</value>
      <webElementGuid>d59987e2-97e0-40f5-bc33-358ee904d1ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum ada'])[3]/following::label[1]</value>
      <webElementGuid>31e10e08-d54a-436e-a1a7-617f2defc2e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ada, belum lengkap'])[3]/following::label[2]</value>
      <webElementGuid>e0eac2ff-a37d-4933-af2d-1a235e85e187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ada, belum lengkap'])[4]/preceding::label[1]</value>
      <webElementGuid>78e7405a-7d05-4193-87ba-7a1e40e6e1dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/label</value>
      <webElementGuid>40fae2e8-4fb9-4a64-bc13-a0cc060b769d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@type = 'radio' and @name = 'assesment.3.answer' and (text() = 'Ada, dan sudah lengkap' or . = 'Ada, dan sudah lengkap')]</value>
      <webElementGuid>ba9d3e5f-c91c-4599-8b08-428c1f0c0942</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
