<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Toast Berhasil Register</name>
   <tag></tag>
   <elementGuidId>a0b5cde4-1840-4528-ac6a-9e857afa482c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::li[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ol > li</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html[@class=&quot;light&quot;]/body[@class=&quot;__className_aaf875&quot;]/section[1]/ol[1]/li[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>9fe0c7b5-11de-476b-b901-24a1454b3376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>974277e5-0a8b-4adb-904b-3d61487aa8ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-atomic</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>26cb7c03-0b6c-4c5b-a91f-1a62bb1d6af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>bd35f565-eb35-4ffd-86a5-a5cc1cb4c094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0d073a43-ab14-48f4-803c-acc2d8683f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-styled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0216e2bf-3b5e-40af-8f37-6b2b29bf43a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mounted</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>57acfcb2-8192-4375-a7de-5f739ac5a81d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-promise</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a1122f5e-ca46-4cf0-93c4-9f87eac0a2f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-removed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0675bd1d-3623-4964-9011-46cedb2caf77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-visible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e409647d-56c0-407e-998f-269249030b1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-y-position</name>
      <type>Main</type>
      <value>bottom</value>
      <webElementGuid>be8e6164-0d88-41d0-9a01-f5d1da16b184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-x-position</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>084415c2-e182-4b0f-8e37-5635db24fe5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4786fb42-d138-4289-a332-b3b83bbb248e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-front</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c8c93b36-1c54-4497-bead-0aa11fcb2042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-swiping</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>69b5b43c-07a5-472e-9f72-89c923ae2174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismissible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b5398d98-279e-4151-89b3-00d492b9c26d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>success</value>
      <webElementGuid>4e3f2223-9b38-4bc3-8f23-8b2ca2d7c621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-swipe-out</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>feda966d-c620-463e-8d77-2266d8e0bda7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6eb14f25-5a26-4fe0-bd10-da95cd2a2ba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Berhasil!Cek email fasdfasdf@yopmail.com untuk memverifikasi akun Anda</value>
      <webElementGuid>4fd11548-ea28-454f-8bbc-bd647dac84be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;light&quot;]/body[@class=&quot;__className_aaf875&quot;]/section[1]/ol[1]/li[1]</value>
      <webElementGuid>1ddba991-2bea-4bf2-910c-7ad7e11d96ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::li[1]</value>
      <webElementGuid>16cc5587-ebff-463c-b4b4-00948703126d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol/li</value>
      <webElementGuid>eff0b35c-8c6b-4382-bc43-582947b93ed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Berhasil!Cek email fasdfasdf@yopmail.com untuk memverifikasi akun Anda' or . = 'Berhasil!Cek email fasdfasdf@yopmail.com untuk memverifikasi akun Anda')]</value>
      <webElementGuid>71ad8199-02fd-4233-874d-2b37b2f37ef4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
