<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Text Field Nomor Telpon Entitas</name>
   <tag></tag>
   <elementGuidId>aba6fff6-7d02-4467-a46b-5ec87dcddd1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='react-aria6963158741-:r10:']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @name = 'institution_phone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>653b0c1f-7b66-4ab9-9371-4508ecb3657c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60bab583-8ecd-4bce-b586-972cddf2c36a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full font-normal bg-transparent !outline-none placeholder:text-foreground-500 focus-visible:outline-none data-[has-start-content=true]:ps-1.5 data-[has-end-content=true]:pe-1.5 text-small h-full is-filled</value>
      <webElementGuid>a393b6a3-58c1-44e4-a1b8-5387f1ff8aae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>No. Telp Entitas</value>
      <webElementGuid>2135fc6b-a608-4b60-a46d-2fbfd12ea7c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-aria6963158741-:r10:</value>
      <webElementGuid>9fe66747-e8d9-46fb-b3d0-4dd61c8d5198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>react-aria6963158741-:r10: react-aria6963158741-:r11:</value>
      <webElementGuid>ea303627-3c20-4ac5-8a21-940a4405fd4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>991d446b-8662-413f-983c-b9f268916f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d6c420b5-fb81-49a8-9765-28a4bd28f335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>institution_phone</value>
      <webElementGuid>2892d739-a89e-4082-9f01-ab4342dca1ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-filled-within</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>083216b6-1d07-4dd0-9878-0d20a36c5468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-filled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>89b8b3bc-4d92-4d70-8097-6b14faf52a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-aria6963158741-:r10:&quot;)</value>
      <webElementGuid>76b9840d-7cf5-4ce6-826f-c891ce3fd8a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='react-aria6963158741-:r10:']</value>
      <webElementGuid>9b27432f-9c50-4c5f-8e59-33beaf7a9b22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div/div/input</value>
      <webElementGuid>813a596e-41e2-43b3-ba9f-21e7ae9b8627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'react-aria6963158741-:r10:' and @type = 'text' and @name = 'institution_phone']</value>
      <webElementGuid>0d9073c6-748d-405f-88ba-8c02b39411d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
