<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Nomor 01 - Ada, dan sudah lengkap</name>
   <tag></tag>
   <elementGuidId>eea030c4-a28f-4ca3-965f-739cfd94d8fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label[name=&quot;assesment.0.answer&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@type = 'radio' and @name = 'assesment.0.answer' and (text() = 'Ada, dan sudah lengkap' or . = 'Ada, dan sudah lengkap')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'radio' and @name = 'assesment.0.answer' and (text() = 'Ada, dan sudah lengkap' or . = 'Ada, dan sudah lengkap')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>22b31159-4e31-4109-9a51-ae03d45f8ec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>group relative max-w-fit inline-flex items-center justify-start cursor-pointer tap-highlight-transparent p-2 -m-2</value>
      <webElementGuid>2f41a871-813b-4005-8983-a7e59637279e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>fb9ca4c6-1291-4832-aedb-e5352eabc4fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>assesment.0.answer</value>
      <webElementGuid>a62de0d4-3053-4faf-b620-6051a46772bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hover</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3870ee21-8699-4fc3-9218-a10bd1999eba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hover-unselected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0459e9b5-c347-4921-b8ed-20eb5e7f6ee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e23e7b6d-54c2-462a-a674-4fbf75ea59fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ada, dan sudah lengkap</value>
      <webElementGuid>e547b221-00f2-4e16-b36c-912d16458ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-aria6291184222-:r1p:&quot;)/div[@class=&quot;flex flex-col flex-wrap gap-2 data-[orientation=horizontal]:flex-row&quot;]/label[@class=&quot;group relative max-w-fit inline-flex items-center justify-start cursor-pointer tap-highlight-transparent p-2 -m-2&quot;]</value>
      <webElementGuid>f4f3534e-e923-4a32-903d-28da75e36791</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@name='assesment.0.answer']</value>
      <webElementGuid>83b5c3ef-6702-42b5-a573-58d618b8f6d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-aria6291184222-:r1p:']/div/label</value>
      <webElementGuid>943305ba-cfde-4785-819f-6556aa28680e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='alice@example.com'])[1]/following::label[1]</value>
      <webElementGuid>706a3976-7129-4c5b-8dc8-788d8b13d0f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='@alice_smith'])[1]/following::label[1]</value>
      <webElementGuid>a94c6a2f-90a9-4291-9543-927174d5a9ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ada, belum lengkap'])[1]/preceding::label[1]</value>
      <webElementGuid>f2b5216b-88e7-4bf5-8001-52adda8353ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>481431c0-6a84-4a0e-b956-854d93791c72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@type = 'radio' and @name = 'assesment.0.answer' and (text() = 'Ada, dan sudah lengkap' or . = 'Ada, dan sudah lengkap')]</value>
      <webElementGuid>acbd9ddc-2d76-443d-b356-90941f56f517</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
