<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Nomor 07 - Ada, dan sudah lengkap</name>
   <tag></tag>
   <elementGuidId>4f13ed9d-23bc-44e9-963e-7221ecbabc7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label[name=&quot;assesment.6.answer&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@name='assesment.6.answer']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'radio' and @name = 'assesment.6.answer' and (text() = 'Ada, dan sudah lengkap' or . = 'Ada, dan sudah lengkap')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>b7c9214e-fbcc-4b2a-8566-c5830a9d3e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>group relative max-w-fit inline-flex items-center justify-start cursor-pointer tap-highlight-transparent p-2 -m-2</value>
      <webElementGuid>8b8b0b81-f6bc-46b3-b0da-39c7f20c138d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>592880fa-7e10-441d-914e-780baf708463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>assesment.6.answer</value>
      <webElementGuid>c4b8668a-00aa-4c0f-a620-2454ed93e23b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hover</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>08c67950-9bd2-4729-a633-e2e4680bc3cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hover-unselected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>806adae6-def4-4fd7-b120-18200971442c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6f9af7ef-2c06-49f8-81ec-f65c9298d032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ada, dan sudah lengkap</value>
      <webElementGuid>09b5db52-d44f-412b-8eab-915807d864ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-aria6291184222-:r6u:&quot;)/div[@class=&quot;flex flex-col flex-wrap gap-2 data-[orientation=horizontal]:flex-row&quot;]/label[@class=&quot;group relative max-w-fit inline-flex items-center justify-start cursor-pointer tap-highlight-transparent p-2 -m-2&quot;]</value>
      <webElementGuid>a088630c-3087-4179-88b7-890b355f7771</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@name='assesment.6.answer']</value>
      <webElementGuid>cfd940c1-ae91-4a57-8231-e666643c3c1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-aria6291184222-:r6u:']/div/label</value>
      <webElementGuid>7c27df0f-3d4a-4322-98f4-57d4a243e8e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum ada'])[6]/following::label[1]</value>
      <webElementGuid>e03f3826-0a8e-4e3e-924a-26b280d10e8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ada, belum lengkap'])[6]/following::label[2]</value>
      <webElementGuid>0b91bf33-fb61-49c8-9504-6279f867a5ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ada, belum lengkap'])[7]/preceding::label[1]</value>
      <webElementGuid>0d2121ae-2328-4b34-ab3a-01f7e071a3fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/div/label</value>
      <webElementGuid>490c4093-a5eb-4c89-aefc-895902f47c73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@type = 'radio' and @name = 'assesment.6.answer' and (text() = 'Ada, dan sudah lengkap' or . = 'Ada, dan sudah lengkap')]</value>
      <webElementGuid>00a4420c-2878-4016-923a-9edf0e9b2444</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
